---
title: "GEOG458_GroupLab1"
author: "Group6"
date: "1/16/2019"
output: html_document
---
##Part 1
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##Section 1, Question 2
China's economic growth has always been questioned by others because from a third-party perspective, we are unsure of how China was able to recover.  China has really impressive statistics when it comes to their GDP.  In 2017, they had a 6.9% growth and also had about 30% of global economic growth.  The Chinese government claim that they have entered into a new economic phase that is more domestic-centered and responsive to popular goods.  But according to [Economic Front](https://economicfront.wordpress.com/2018/06/05/the-chinese-economy-problems-and-prospects/), there is a graph that shows China's growth rate between 2011 to 2016 actually dropped significantly before the growth in 2017.  There were cases that GPD data was manipulated to attempt to meet standards, such as Inner Mongolia admitted to falsifying data back in 2016.

In [China's Economic Data: An Accurate Refelction, or Just Smoke and Mirrors](https://www.stlouisfed.org/publications/regional-economist/second-quarter-2017/chinas-economic-data-an-accurate-reflection-or-just-smoke-and-mirrors ), they have a few suggestions to help collect *better* GPD.  They have three mothods that we can consder; energy consumption, indexed GDP proxies, and luminosity.  Because China does consume a lot of energy, changes in this particular area could help collect data.  We can think of it as China consumes energy to make products which can be recording as production.  A second method, indexed GDP proxies.  Indexing will measure from quarter-to-quarter but with consistency it can show quarterly growth to yearly growth.  The last method is luminsoity and that means to use satellite data that will measure the intensity of man-made night lights.  This method is can avoid falsification and misreporting because this method would be able to track consumption of all goods that requires light.  
